# Generated by Django 3.2.21 on 2023-11-09 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FlightApp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactMessage',
        ),
    ]
